services:
  - type: web
    name: blaze-xiters-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
